//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistsCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibition
    {
        public int ID_exhibition { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID_user { get; set; }
        public byte[] Image { get; set; }
        public string Information { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
