//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistsCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution_Hall
    {
        public int ID_institution { get; set; }
        public int ID_hall { get; set; }
        public int ID { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Institution Institution { get; set; }
    }
}
