//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtistsCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Painting_artist
    {
        public int ID_painting_artist { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Creation_date { get; set; }
        public string Execution { get; set; }
        public byte[] Image { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> ID_user { get; set; }
        public bool Accepted { get; set; }
    }
}
